<?php
// start the session
session_start();
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="../css/dashboard.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&family=Press+Start+2P&display=swap" rel="stylesheet">
  </head>
  <body>
    <div id="modal" class="modal">
      <div class="content">
        <span class="close" onclick="closeModal()">&times;</span>
        <h2>Game Rules</h2>
        <p id="demo"></p>
      </div>
    </div>
    <div class="container">
      <div class="header">
        <h2> <?php
    // check if the user is logged in
    if (isset($_SESSION['user_id'])) {
        // display the user's name
        echo "Agent:" . $_SESSION['user_name'];
    } else {
        // redirect to the login page
        header('Location: ../login/signin.php');
        exit();
    }
    ?> </h2>
        <h1>Detective Board</h1>
        <button class="button" onclick="openModal()">Rules</button>
        <a href="../login/logout.php">Logout</a>
      </div>
      <div class="flex-container">
        <div class="flex-child">
          <!-- Image Map Generated by http://www.image-map.net/ -->
          <img id="Image-Maps-Com-image-maps-2023-04-20-165024" src="../images/board.png" border="0" width="1362" height="1114" orgWidth="1362" orgHeight="1114" usemap="#image-maps-2023-04-20-165024" alt="" />
          <map name="image-maps-2023-04-20-165024" id="ImageMapsCom-image-maps-2023-04-20-165024">
            <area shape="rect" coords="1360,1112,1362,1114" alt="Image Map" style="outline:none;" title="Image Map" href="https://www.image-maps.com/" />
            <area id="Level1" alt="Level1" title="Level1" href="../game/crime_scene_investigation.php" shape="poly" coords="155,130,181,434,267,439,305,407,333,404,367,411,448,493,523,494,531,460,518,384,516,351,522,236,568,230,571,190,698,187,751,205,818,194,818,169,802,137,765,153,725,153,702,147,604,146,574,128,510,109,470,130,420,157,349,157,363,126,280,95,266,121,210,98,192,117" style="outline:none;" target="_self" />
            <area id="Level2" alt="Level2" title="Level2" href="../game/forensic_analysis.php" shape="poly" coords="568,255,565,491,550,491,537,537,590,547,605,542,619,548,646,549,645,530,644,525,805,529,844,491,897,536,969,532,1005,544,1054,502,1060,510,1065,506,1087,508,1095,520,1104,506,1120,514,1155,505,1163,520,1168,508,1183,521,1213,509,1223,518,1220,348,1226,308,1231,115,1210,106,1204,117,1173,108,1155,118,1133,106,1120,108,1099,127,1082,112,1064,110,1053,125,1034,121,1025,111,975,126,941,104,911,104,876,134,869,233,809,250" style="outline:none;" target="_self" />
            <area id="Level3" alt="Level3" title="Level3" href="../game/cipher_decryption.php" shape="poly" coords="156,578,146,764,157,884,469,876,503,878,603,852,666,877,752,867,896,878,901,892,941,867,944,884,1021,902,1098,887,1181,877,1185,728,1206,671,1206,563,1047,569,1044,597,891,622,748,638,711,580,595,563,487,579,497,535,458,544,416,532,417,581,206,505" style="outline:none;" target="_self" />
          </map>
        </div>
      </div>
    </div>
    <script>
      function openModal() {
        document.getElementById("modal").style.display = "block";
      }

      function closeModal() {
        document.getElementById("modal").style.display = "none";
      }
    </script>
    <script>
      var i = 0;
      var txt = 'A person is brutally murdered in his house.The room is dim and corpse is with blood.Hello Agent! You are welcome to solve the case and find the mystery.Here the detective board consists of 3 levels. The "1" enclosed with blue border redirects you to the first level, "2" with green border and "3" with pink border directs you to their respective levels.In each level you are provided with clues.With these clues you need to catch the killer with in less time.';
      var speed = 100;

      function typeWriter() {
        if (i < txt.length) {
          document.getElementById("demo").innerHTML += txt.charAt(i);
          i++;
          setTimeout(typeWriter, speed);
        }
      }
      typeWriter();
    </script>
  </body>
</html>